Numpy:

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 6], 
              [2, 8], 
              [3, 11], 
              [3, 10], 
              [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [3]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

In [5]:
a_centered = np.subtract(a, mean_a)
a_centered   

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [6]:
a_centered_sp = a_centered[:,0] @ a_centered[:,1]
a_centered_sp

8.0

In [9]:
N = a.shape[0]
N

5

In [10]:
n_centered = a_centered_sp / (N - 1)
n_centered

2.0

In [11]:
m = np.cov(a.T)
m

array([[1. , 2. ],
       [2. , 4.3]])

In [13]:
m[0, -1] == 2

True

Pandas:

In [14]:
import pandas as pd

In [15]:
authors = pd.DataFrame({
    'author_id': [1, 2, 3],
    'author_name': ['Turgenev', 'Chekhov', 'Ostrovsky']
})
authors

author_id author_name
0          1    Turgenev
1          2     Chekhov
2          3   Ostrovsky

In [16]:
book = pd.DataFrame({
    'author_id': [1, 1, 1, 2, 2, 3, 3],
    'book_title': ['Fathers and Sons', 'Rudin', 'Noble Nest', 'Thick and Thin', 'Lady with a dog', 'Thunderstorm', 'Talents and fans'],
    'price': [450, 300, 350, 500, 450, 370, 290]
})
book

author_id        book_title  price
0          1  Fathers and Sons    450
1          1             Rudin    300
2          1        Noble Nest    350
3          2    Thick and Thin    500
4          2   Lady with a dog    450
5          3      Thunderstorm    370
6          3  Talents and fans    290

In [17]:
authors_price = pd.merge(authors, book, on='author_id', how='outer')
authors_price

author_id author_name        book_title  price
0          1    Turgenev  Fathers and Sons    450
1          1    Turgenev             Rudin    300
2          1    Turgenev        Noble Nest    350
3          2     Chekhov    Thick and Thin    500
4          2     Chekhov   Lady with a dog    450
5          3   Ostrovsky      Thunderstorm    370
6          3   Ostrovsky  Talents and fans    290

In [20]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name        book_title  price
3          2     Chekhov    Thick and Thin    500
0          1    Turgenev  Fathers and Sons    450
4          2     Chekhov   Lady with a dog    450
5          3   Ostrovsky      Thunderstorm    370
2          1    Turgenev        Noble Nest    350

In [39]:
df1 = authors_price.groupby('author_name').agg({'price': 'min'}).rename(columns={'price':'min_price'})
df2 = authors_price.groupby('author_name').agg({'price': 'max'}).rename(columns={'price':'max_price'})
df3 = authors_price.groupby('author_name').agg({'price': 'mean'}).rename(columns={'price':'mean_price'})

authors_stat=pd.concat([df1, df2, df3], axis = 1)
authors_stat

#Данный пункт нашел в интернете, мне кажется есть более простое решение, но как не бился - не нашел

min_price  max_price  mean_price
author_name                                  
Chekhov            450        500  475.000000
Ostrovsky          290        370  330.000000
Turgenev           300        450  366.666667

In [37]:
authors_price['cover'] = ['solid', 'soft', 'soft', 'solid', 'solid', 'soft', 'solid']
authors_price

author_id author_name        book_title  price  cover
0          1    Turgenev  Fathers and Sons    450  solid
1          1    Turgenev             Rudin    300   soft
2          1    Turgenev        Noble Nest    350   soft
3          2     Chekhov    Thick and Thin    500  solid
4          2     Chekhov   Lady with a dog    450  solid
5          3   Ostrovsky      Thunderstorm    370   soft
6          3   Ostrovsky  Talents and fans    290  solid

In [40]:
?pd.pivot_table

In [44]:
book_info = pd.pivot_table(authors_price, values='price', index=['author_name'], columns=['cover'], 
                           aggfunc=np.sum, fill_value=0)
book_info

cover        soft  solid
author_name             
Chekhov         0    950
Ostrovsky     370    290
Turgenev      650    450

In [43]:
book_info.to_pickle('book_info.pkl')
book_info

cover        soft  solid
author_name             
Chekhov         0    950
Ostrovsky     370    290
Turgenev      650    450

In [50]:
book_info2 = pd.read_pickle('book_info.pkl')
book_info2

cover        soft  solid
author_name             
Chekhov         0    950
Ostrovsky     370    290
Turgenev      650    450

In [51]:
book_info == book_info2
 

cover        soft  solid
author_name             
Chekhov      True   True
Ostrovsky    True   True
Turgenev     True   True